add_all_link:
  fields:
    group:
      required: true
      selector:
        number:
          min: 0
          max: 255
    mode:
      required: true
      selector:
        select:
          options:
            - "controller"
            - "responder"
delete_all_link:
  fields:
    group:
      required: true
      selector:
        number:
          min: 0
          max: 255
load_all_link_database:
  fields:
    entity_id:
      required: true
      example: "light.1a2b3c"
      selector:
        text:
    reload:
      default: false
      selector:
        boolean:
print_all_link_database:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: insteon
print_im_all_link_database:
x10_all_units_off:
  fields:
    housecode:
      required: true
      selector:
        select:
          options:
            - "a"
            - "b"
            - "c"
            - "d"
            - "e"
            - "f"
            - "g"
            - "h"
            - "i"
            - "j"
            - "k"
            - "l"
            - "m"
            - "n"
            - "o"
            - "p"
x10_all_lights_on:
  fields:
    housecode:
      required: true
      selector:
        select:
          options:
            - "a"
            - "b"
            - "c"
            - "d"
            - "e"
            - "f"
            - "g"
            - "h"
            - "i"
            - "j"
            - "k"
            - "l"
            - "m"
            - "n"
            - "o"
            - "p"
x10_all_lights_off:
  fields:
    housecode:
      required: true
      selector:
        select:
          options:
            - "a"
            - "b"
            - "c"
            - "d"
            - "e"
            - "f"
            - "g"
            - "h"
            - "i"
            - "j"
            - "k"
            - "l"
            - "m"
            - "n"
            - "o"
            - "p"
scene_on:
  fields:
    group:
      required: true
      selector:
        number:
          min: 0
          max: 255
scene_off:
  fields:
    group:
      required: true
      selector:
        number:
          min: 0
          max: 255
add_default_links:
  fields:
    entity_id:
      required: true
      example: "light.1a2b3c"
      selector:
        text:
update_property:
  fields:
    target_device:
      required: true
      selector:
        device:
          integration: insteon
    prop_name:
      required: true
      example: "led_off"
      selector:
        select:
          custom_value: true
          options:
            - "ambient_light_intensity"
            - "auto_led"
            - "backlight"
            - "battery_level"
            - "blink_on_error_off"
            - "blink_on_error_on"
            - "blink_on_tx_on"
            - "button_lock_on"
            - "celsius"
            - "change_delay"
            - "cleanup_report_on"
            - "crc_error_count"
            - "database_delta"
            - "deadman"
            - "disable_auto_linking"
            - "dual_line_on"
            - "duration_high"
            - "duration_low"
            - "forward_on"
            - "grouped_on"
            - "hardware_led_off"
            - "hardware_light_sensitivity"
            - "hardware_night_mode"
            - "hardware_send_on_only"
            - "hardware_timeout"
            - "ignore_jumper_on"
            - "key_beep_on"
            - "led_brightness"
            - "led_dimming"
            - "led_off"
            - "led_on"
            - "light_sensitivity"
            - "link_to_ff_group"
            - "load_sense_on"
            - "momentary_delay"
            - "momentary_line_on"
            - "monitor_mode"
            - "motion_timeout"
            - "multi_send_on"
            - "night_mode_only"
            - "not_3_way"
            - "on_level"
            - "powerline_disable_on"
            - "program_lock_on"
            - "ramp_rate_in_seconds"
            - "relay_mode"
            - "repeat_closed_on"
            - "repeat_open_on"
            - "resume_dim_on"
            - "reversed_on"
            - "rf_disable_on"
            - "send_on_only_on"
            - "sense_sends_off"
            - "signal_to_noise_failure_count"
            - "software_support_on"
            - "stay_awake_on"
            - "three_way_on"
            - "time_24_hour_format"
            - "toggle_button_a"
            - "toggle_button_b"
            - "toggle_button_c"
            - "toggle_button_d"
            - "toggle_button_e"
            - "toggle_button_f"
            - "toggle_button_g"
            - "toggle_button_h"
            - "two_groups_on"
            - "x10_off"
    prop_value:
      required: true
      example: "true"
      selector:
        select:
          custom_value: true
          options:
            - "true"
            - "false"
            - "toggle"
            - "on_only"
            - "off_only"
            - "latching"
            - "momentary_a"
            - "momentary_b"
            - "momentary_c"
